version: "3"

services:
    redis:
        image: redis
        restart: always
        command:
            sh -c "redis-server"
        ports:
            - "6379:6379"

    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        ports:
            - "8000:8000"
        command:
            sh -c "python manage.py makemigrations --no-input &&
                   python manage.py migrate --no-input &&
                   python manage.py collectstatic --no-input &&
                   exec uvicorn FruitCompany.asgi:application --host 0.0.0.0 --port 8000"

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        depends_on:
            - web
        ports:
            - "80:80"
        volumes:
            - ./static/:/static/

    celery_worker_fruit:
        restart: always
        build:
            context: .
        command:
            sh -c "celery -A FruitCompany worker -l info -Q FruitQueue -c 1"
        volumes:
            - ./:/usr/src/app
        depends_on:
            - redis

    celery_worker_default:
        restart: always
        build:
            context: .
        command:
            sh -c "celery -A FruitCompany worker -l info -Q DefaultQueue"
        volumes:
            - ./:/usr/src/app
        depends_on:
            - redis

    celery_worker_loop:
        restart: always
        build:
            context: .
        command:
            sh -c "celery -A FruitCompany worker -l info -Q LoopQueue -c 1"
        volumes:
            - ./:/usr/src/app
        depends_on:
            - redis

    celery_worker_joker:
        restart: always
        build:
            context: .
        command:
            sh -c "celery -A FruitCompany worker -l info -Q JokerQueue -c 1"
        volumes:
            - ./:/usr/src/app
        depends_on:
            - redis


    celery_beat:
        restart: always
        build:
            context: .
        command:
            sh -c "celery -A FruitCompany beat -l info"
        volumes:
            - ./:/usr/src/app
        depends_on:
            - redis
            - celery_worker_fruit