# Generated by Django 3.2.4 on 2022-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_tasktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktime',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
